config/routes.rb
Rails.application.routes.draw do

  get 'blog' => 'blog#index'

  get 'blog/article/:id' => 'blog#show'

  get 'portfolio/makkrol' => 'portfolio#makkrol'

  get 'portfolio/bobolo' => 'portfolio#bobolo'

  get 'portfolio/nao' => 'portfolio#nao'

  get 'portfolio/le-bois-sainte-anastasie' => 'portfolio#le_bois_sainte_anastasie'

  get 'portfolio/la-maison-du-cafe' => 'portfolio#la_maison_du_cafe'

  get 'portfolio/il-et-elle-mode' => 'portfolio#iletelle_mode'

  get 'portfolio/olialima' => 'portfolio#olialima'

  get 'portfolio/express-informatique' => 'portfolio#express_informatique'

  get 'portfolio/bambou-lounge' => 'portfolio#bambou_lounge'

  get 'portfolio/lilac-travel' => 'portfolio#lilac_travel'

  get 'portfolio/solim' => 'portfolio#solim'

  get 'portfolio/smile-restaurant' => 'portfolio#smile'

  get 'portfolio/mahou' => 'portfolio#mahou'

  get 'portfolio/olympic-gaming' => 'portfolio#olympic_gaming'

  get 'portfolio/bhent' => 'portfolio#bhent'

  get 'portfolio/black-and-white' => 'portfolio#black_and_white'

  get 'portfolio' => 'portfolio#index'

  get 'about-us-agency' => 'home#about_us'

  get 'expertise' => 'home#expertise'

  get 'branding-design' => 'home#branding_design'

  get 'websites-digital' => 'home#websites_digital'

  get 'marketing-advertising' => 'home#marketing_advertising'

  get 'print-packaging' => 'home#print_packaging'

  root 'home#index'

  get 'contact-us' => 'contact_us#index'
  post 'contact-us', to: 'contact_us#create'
  get '/change_locale/:locale', to: 'language_settings#change_locale', as: :change_locale


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, allow_nil: true


	validates :content, presence: true, length: {maximum: 255 }, allow_nil: true

	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
  	if cookies[:bhent_locale] && I18n.available_locales.include?(cookies[:bhent_locale].to_sym)
  		l = cookies[:bhent_locale].to_sym
  	  else
  	  	l = I18n.default_locale
  	  	cookies.permanent[:bhent_locale] = l
  	end
  	I18n.locale = l
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end

  def show
  	
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  	@message = Contact.new
  end
  def create
  	@message = Contact.new(contact_params)
  	if @message.save
  		flash[:success] = "Message sent!"
  		redirect_to contact_us_url
  	else
  		render 'index'
  	end
  end

  private
  def contact_params
  	params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about_us
  end

  def expertise
  end

  def branding_design
  end

  def websites_digital
  end

  def marketing_advertising
  end

  def print_packaging
  end

end

app/controllers/language_settings_controller.rb
class LanguageSettingsController < ApplicationController

	def change_locale
		l = params[:locale].to_s.strip.to_sym
		l = I18n.default_locale unless I18n.available_locales.include?(l)

		cookies.permanent[:bhent_locale] = l
		redirect_to request.referer || root_url
	end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  def index
  end

  def black_and_white
  end

  def bhent
  end

  def le_bois_sainte_anastasie
  end

  def la_maison_du_cafe
  end

  def iletelle_mode
  end

  def olialima
  end

  def nao
  end

  def bobolo
  end

  def makkrol
  end

  def bambou_lounge
  end

  def lilac_travel
  end

  def solim
  end

  def mahou
  end

  def express_informatique
  end

  def smile
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/langauge_settings_helper.rb
module LangaugeSettingsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/blog/shared/_back.html.erb
<div class="small-2 columns center_link">
  <a href="/blog" title="Back">
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" x="0" y="0" width="20" height="20" viewBox="296.5 494.5 20 20" enable-background="new 296.5 494.5 20 20" xml:space="preserve"><path fill-rule="evenodd" clip-rule="evenodd" d="M296.5 494.5h8v8h-8V494.5z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M308.5 494.5h8v8h-8V494.5z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M296.5 506.5h8v8h-8V506.5z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M308.5 506.5h8v8h-8V506.5z"/></svg>				
    </a>
</div>

app/views/blog/shared/_header_blog.html.erb
<div class="logo-holder">
  <a href="/" class="logolink" title="WerkStatt Agency">
    <%= image_tag('logo.png', :class => "logoimg logo-dark", :alt => "Bhent Branding Agency") %>
    <%= image_tag('logo_light-top.png', :class => "logoimg logo-light", :alt => "Bhent Branding Agency") %>
  </a>
</div>
<div>
  <a href="#" class="mobile-toggle">
    <span></span><span></span><span></span>
  </a>
</div>

app/views/contact_us/_message.html.erb
<%= form_for(@message, url: contact_us_path) do |f| %>
   <% if @message.errors.any? %>
    <div id="error_explanation">
      <p><%= t('errors.template.body')%></p>
      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= raw message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">

      <div class="small-12 large-6 columns">
        <%= f.label t('contact.form.name') %>
        <span class="wpcf7-form-control-wrap your-firstname">
          <%= f.text_field :name, class: 'wpcf7-form-control wpcf7-text wpcf7-validates-as-required full' %>
        </span>
      </div>
      <div class="small-12 large-6 columns">
        <%= f.label t('contact.form.email') %>
        <span class="wpcf7-form-control-wrap your-email">
                        
          <%= f.email_field :email, class: 'wpcf7-form-control wpcf7-text wpcf7-validates-as-required full' %>
        </span>
      </div>
      <div class="small-12 columns">
        <%= f.label t('contact.form.message')%>
        <span class="wpcf7-form-control-wrap your-message">
          <%= f.text_area :content, class: 'wpcf7-form-control wpcf7-textarea full' %>
        </span>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <%= f.submit t('contact.form.send'), class: 'wpcf7-form-control wpcf7-submit btn' %>
      </div>
    </div>
    <div class="wpcf7-response-output wpcf7-display-none">
                    
    </div>

<%end%>

app/views/home/index.html.erb
<%= title t('home.index.welcome') %>
<style type="text/css" data-type="vc_shortcodes-custom-css">.vc_custom_1475072484539{margin-top: 100px !important;padding-top: 10vh !important;padding-bottom: 10vh !important;}.vc_custom_1475000210039{padding-top: 10vh !important;padding-bottom: 10vh !important;}.vc_custom_1475009886874{padding-top: 10vh !important;padding-bottom: 10vh !important;background-color: #f9f9f9 !important;}.vc_custom_1475009891356{padding-top: 16vh !important;padding-bottom: 16vh !important;background: #25282a url(http://mrf0q11hs9f5smjcwivxd3qm.wpengine.netdna-cdn.com/werkstatt-agency-simple/wp-content/uploads/sites/3/2016/09/h13_01.jpg?id=284) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}</style><noscript><style type="text/css"> .wpb_animate_when_almost_visible { opacity: 1; }</style></noscript>

<%= render "layouts/shared/logo_header_menu" %>

<div role="main" class="cf">
    <div class=" post-282 page type-page status-publish hentry">
      <div class="row wpb_row row-fluid align-center vc_custom_1475072484539">
        <div class="text-center wpb_column columns small-12 medium-12 large-10 medium-10 thb-dark-column">
          <div class="vc_column-inner ">
            <div class="wpb_wrapper">
              <div class="wpb_text_column wpb_content_element  ">
                <div class="wpb_wrapper">
                  <h6><%= t('home.index.welcome')%></h6>
                </div>
              </div>
              <div id="thb-autotype-85" class="thb-autotype">
                <h1 class="title-header">
                  <strong>

                    <span style="font-size: 32px; font-weight: bold;"><%= t('home.index.stable')%></span><br />
                    <span style="font-size: 26px; font-weight: lighter;"><%= t('home.index.stable2')%></span><br />
                    <span style="font-size: 26px; font-weight: lighter;"><%= t('home.index.stable3')%>
                    <div class="thb-autotype-entry" data-thb-loop="1" data-strings="[&quot;<%=t('home.index.corporate_identities') %>&quot;,&quot;<%=t('home.index.logos') %>&quot;,&quot;<%=t('home.index.interiors') %>&quot;,&quot;<%=t('home.index.brand_design') %>&quot;,&quot;<%=t('home.index.corporate_communications') %>&quot;,&quot;<%=t('home.index.marketing_campaigns') %>&quot;,&quot;<%=t('home.index.website') %>&quot;,&quot;<%=t('home.index.mobile_application') %>&quot;]"></div>
                      </span>
                  </strong>
                </h1>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--Test portfolio -->
      <div class="row wpb_row row-fluid no-row-padding full-width-row no-column-padding">
        <div class="wpb_column columns small-12 medium-12 thb-dark-column">
          <div class="vc_column-inner ">
            <div class="wpb_wrapper">
              <div class="row expanded thb-portfolio masonry masonry-style4 style1 " id="portfolio-section-396" data-thb-animation="thb-animate-from-bottom" data-filter="thb-filter-396">
                <div class="columns small-12 medium-6 large-3 padding-2 title-center thb-animate-from-bottom light-title  thb-cat-website  style1 post-39 portfolio type-portfolio status-publish has-post-thumbnail hentry portfolio-category-website" id="portfolio-39">
                  <div class="portfolio-holder">
                    <div class="thb-placeholder black-white"></div>
                    <a href="portfolio/black-and-white" title="Black&amp;White" class="portfolio-link" data-size="570x902">
                      <h2><span>Black&amp;White</span></h2>
                      <aside class="thb-categories"><span><%= t('portfolio.index.categiries_portfolio1')%></span></aside>
                    </a>
                  </div>
                </div>
                <div class="columns small-12 medium-6 large-3 padding-1 title-center thb-animate-from-bottom light-title  thb-cat-illustration  style1 post-41 portfolio type-portfolio status-publish has-post-thumbnail hentry portfolio-category-illustration" id="portfolio-41">
                  <div class="portfolio-holder">
                    <div class="thb-placeholder olympic-gaming"></div>
                    <a href="/portfolio/olympic-gaming" title="Olympic Gaming" class="portfolio-link" data-size="961x760">
                      <h2><span>Olympic Gaming</span></h2>
                      <aside class="thb-categories"><span><%= t('portfolio.index.categiries_portfolio2')%></span></aside>
                    </a>
                  </div>
                </div>
                <div class="columns small-12 medium-6 large-6 padding-half title-center thb-animate-from-bottom light-title  thb-cat-inspiration  style1 post-47 portfolio type-portfolio status-publish has-post-thumbnail hentry portfolio-category-inspiration" id="portfolio-47">
                  <div class="portfolio-holder">
                    <div class="thb-placeholder mahou"></div>
                    <a href="/portfolio/mahou" title="Mahou" class="portfolio-link" data-size="1191x760">
                      <h2><span>Mahou</span></h2>
                      <aside class="thb-categories"><span><%= t('portfolio.index.categiries_portfolio3')%></span></aside>
                    </a>
                  </div>
                </div>
                <div class="columns small-12 medium-6 large-6 padding-half title-center thb-animate-from-bottom light-title  thb-cat-inspiration  style1 post-47 portfolio type-portfolio status-publish has-post-thumbnail hentry portfolio-category-inspiration" id="portfolio-47">
                  <div class="portfolio-holder">
                    <div class="thb-placeholder bhent"></div>
                    <a href="/portfolio/bhent" title="Bhent" class="portfolio-link" data-size="1191x760">
                      <h2><span>Bhent</span></h2>
                      <aside class="thb-categories"><span><%= t('portfolio.index.categiries_portfolio4')%></span></aside>
                    </a>
                  </div>
                </div>
                <div class="columns small-12 medium-6 large-3 padding-1 title-center thb-animate-from-bottom light-title  thb-cat-motion  style1 post-57 portfolio type-portfolio status-publish has-post-thumbnail hentry portfolio-category-motion" id="portfolio-57">
                  <div class="portfolio-holder">
                    <div class="thb-placeholder lilac"></div>
                    <a href="/portfolio/lilac-travel" title="Lilac Travel" class="portfolio-link" data-size="961x760">
                      <h2><span>Lilac Travel</span></h2>
                      <aside class="thb-categories"><span><%= t('portfolio.index.categiries_portfolio5')%></span></aside>
                    </a>
                  </div>
                </div>
                <div class="thb-preloader">
                  <svg class="thb-preloader-icon-hexagon" width="51" height="55" viewBox="0 0 34 38">
                    <path class="preloader-path" stroke="#ef173b" stroke-dasharray="70 32" stroke-width="2" stroke-linejoin="round" stroke-dashoffset="0" d="M29.437 8.114L19.35 2.132c-1.473-.86-3.207-.86-4.68 0L4.153 8.114C2.68 8.974 1.5 10.56 1.5 12.28v11.964c0 1.718 1.22 3.306 2.69 4.165l10.404 5.98c1.47.86 3.362.86 4.834 0l9.97-5.98c1.472-.86 2.102-2.45 2.102-4.168V12.28c0-1.72-.59-3.306-2.063-4.166z">
                    </path>
                  </svg>
                </div>
              </div>
              <div class="columns small-12 medium-12 large-12 ">
                <h6 style="text-align: center; position: relative; top: 40px;">
                  <%= link_to t('portfolio.index.view_full_portfolio'), portfolio_path %>
                </h6>
              </div>
              <div class="vc_empty_space"  style="height: 20px" ><span class="vc_empty_space_inner"></span></div>
              <div class="vc_empty_space"  style="height: 20px" ><span class="vc_empty_space_inner"></span></div>
            </div>
          </div>
        </div>
      </div>
      <div class="vc_empty_space"  style="height: 20px" ><span class="vc_empty_space_inner"></span></div>
      <!-- End test portfolio-->
      <!-- What we do -->
      <div class="synopsis">
        <div class="row">
          <div class="columns small-12 medium-12 large-10 large-offset-2">
            <h4 style="text-align:;"><%=t('home.index.synopsis') %></h4>
          </div>
        </div>
        <div class="row">
          <div class="columns small-12 medium-6 large-5 large-offset-2">
            <p>
              <%=t('home.index.synopsis1') %><br><br>
              <%= t('home.index.synopsis3') %><br>
              <%= t('home.index.synopsis4') %>
            </p>
          </div>
          <div class="columns small-12 medium-6 large-5">
            <h5 style="text-align: ; font-size: 18px; letter-spacing: 0.02em">
              <%= link_to t('home.index.branding_design'), branding_design_path %><br/>
              <%= link_to t('home.index.websites_digital'), websites_digital_path %><br/>
              <%= link_to t('home.index.marketing_advertising'), marketing_advertising_path %><br/>
              <%= link_to t('home.index.print_packaging'), print_packaging_path %>
            </h5>
            <h6>
              <%= link_to t('home.index.view_expertise'), expertise_path %>
            </h6>
          </div>
        </div>
        <div class="vc_empty_space"  style="height: 20px" ><span class="vc_empty_space_inner"></span></div>
      </div>
      <!-- End what we do -->
    </div>
 </div>
 <!-- End role["main"] -->

app/views/layouts/shared/_footer.html.erb
<div class="fixed-footer-container">
  <!-- Start Footer -->
  <footer id="footer" class="footer  dark full-width-footer">
    <div class="row">
      <div class="small-12 medium-6 large-3 columns">
        <div id="text-4" class="widget cf widget_text">
          <div class="textwidget">
            <%= image_tag('logo_light.png', :class => "logoimg logo-light", :alt => "Bhent Branding Agency") %>
          </div>
        </div>
      </div>
      <div class="small-12 medium-6 large-3 columns">
        <div id="text-2" class="widget cf widget_text"><h6><%=t('layouts.shared.footer.address') %></h6>
          <div class="textwidget">
            <p>
              <%=t('layouts.shared.footer.address_street') %><br/>
              <%=t('layouts.shared.footer.address_box') %><br/>
              <%=t('layouts.shared.footer.address_town') %>
            </p>
          </div>
        </div>
      </div>
      <div class="small-12 medium-6 large-3 columns">
        <div id="nav_menu-2" class="widget cf widget_nav_menu">
          <h6><%= t('layouts.shared.footer.intouch') %> </h6>
          <div class="menu-secondary-container">
            <address>
              <strong>M.</strong>
              <a href="callto:695-953-666">695-953-666</a> / <a href="callto:652-199-227">652-199-227</a> <br>
              <strong>E.</strong>
              <a href="mailto:hello@bhent.xyz">hello@bhent.xyz</a>
            </address>
            <h6><%= t('layouts.shared.footer.follow')%></h6>
            <ul id="menu-secondary-1" class="menu">
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32"><a target="_blank" href="https://www.facebook.com/bhentbranding/">Facebook</a></li>
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-33"><a target="_blank" href="https://twitter.com/bhentbranding/">Twitter</a></li>
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-35"><a target="_blank" href="https://www.instagram.com/bhentbranding/">Instagram</a></li>
              <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-36"><a target="_blank" href="https://www.linkedin.com/company/bhent-ltd/">Linkedin</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="small-12 medium-6 large-3 columns">
        <div id="text-3" class="widget cf widget_text">
          <h6><%= t('layouts.shared.footer.navigate') %> </h6>
          <ul id="menu-secondary-1" class="menu">
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32">
              <%= link_to t('menu.item.home'), root_path %>
            </li>
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-33">
              <%= link_to t('menu.item.portfolio'), portfolio_path %>
            </li>
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-33">
              <%= link_to t('menu.item.expertise'), expertise_path %>
            </li>
            <!--<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-34">-->
              <!--<%= link_to t('menu.item.blog'), blog_path %>-->
            <!--</li>-->
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-35">
              <%= link_to t('menu.item.about'), about_us_agency_path %>
            </li>
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-36">
              <%= link_to t('menu.item.contact'), contact_us_path %>
            </li>
          </ul>
          <h6><%= t('layouts.shared.footer.copyright')%></h6>
          <div class="textwidget">
            <p>&copy; 2017 Bhent. <%= t('layouts.shared.footer.copyright_allright')%></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End Footer -->
</div>
<!-- End .fixed-footer-container -->

app/views/layouts/shared/_header.html.erb
<!-- Start Mobile Menu -->
<nav id="mobile-menu" class="dark style1">
  <a href="#" class="thb-close">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" enable-background="new 0 0 64 64">
      <g fill="none" stroke="#000" stroke-width="2" stroke-miterlimit="10">
        <path d="m18.947 17.15l26.1 25.903"/>
        <path d="m19.05 43.15l25.902-26.1"/>
      </g>
    </svg>
  </a>
  <div class="menubg-placeholder"></div>
  <div class="custom_scroll" id="menu-scroll">
    <div>
      <div class="mobile-menu-top">
        <div class="thb-language-switcher" id="thb_language_selector">

          
          <% if cookies[:bhent_locale] == "en" %>
            <%= link_to t('menu.languages.fr'), change_locale_path(:fr)%>
            <%= link_to t('menu.languages.en'), change_locale_path(:en), class: 'active'  %>
          <%else%>
            <%= link_to t('menu.languages.fr'), change_locale_path(:fr), class: 'active' %>
            <%= link_to t('menu.languages.en'), change_locale_path(:en) %>
          <%end%>


        </div>
        <ul id="menu-navigation" class="thb-mobile-menu">
          <li id="menu-item-287" class=" menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-282 current_page_item menu-item-287">
            <div class="link_container">
              <div class="link_inner">
                <%= link_to t('menu.item.home'), root_path, :data => {:content => "Home", :menubg => image_path('chicane_brand_7.jpg')} %>
              </div>
            </div>
          </li>
          <li id="menu-item-300" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-300">
            <div class="link_container">
              <div class="link_inner">
                <%= link_to t('menu.item.portfolio'), portfolio_path, :data => {:content => "Portfolio", :menubg => image_path('portfolio.jpg')} %>
              </div>
            </div>
          </li>
          <li id="menu-item-300" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-300">
            <div class="link_container">
              <div class="link_inner">
                <%= link_to t('menu.item.expertise'), expertise_path, :data => {:content => "Expertise", :menubg => image_path('expertise.jpg')} %>
              </div>
            </div>
          </li>
          <!--<li id="menu-item-30" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-30">-->
            <!--<div class="link_container">-->
              <!--<div class="link_inner">-->
                <!--<%= link_to t('menu.item.blog'), blog_path, :data => {:content => "Blog", :menubg => image_path('thumb_IMG_0018_1024.jpg')} %>-->
              <!--</div>-->
            <!--</div>-->
          <!--</li>-->
          <li id="menu-item-204" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-204">
            <div class="link_container">
              <div class="link_inner">
                <%= link_to t('menu.item.about'), about_us_agency_path, :data => {:content => "About Us", :menubg => image_path('about_us.jpg')} %>
              </div>
            </div>
          </li>
          <li id="menu-item-288" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-288">
            <div class="link_container">
              <div class="link_inner">
                <%= link_to t('menu.item.contact'), contact_us_path, :data => {:content => "Contact", :menubg => image_path('contact_us.jpg')} %>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="mobile-menu-bottom">
        <ul id="menu-secondary" class="thb-secondary-menu row small-up-2">
          <li id="menu-item-32" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32 column"><a target="_blank" href="https://www.facebook.com/bhentbranding/">Facebook</a></li>
          <li id="menu-item-33" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-33 column"><a target="_blank" href="https://twitter.com/bhentbranding/">Twitter</a></li>
          <li id="menu-item-35" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-35 column"><a target="_blank" href="https://www.instagram.com/bhentbranding/">Instagram</a></li>
          <li id="menu-item-37" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-37 column"><a target="_blank" href="https://www.linkedin.com/company/bhent-ltd/">Linkedin</a></li>
        </ul>
        <div class="menu-footer">
          <div>
            <p>&copy; 2016 Bhent. <%= t('layouts.shared.footer.copyright_allright')%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
<!-- End Mobile Menu -->